/**
 * Filipino profanity terms adapted from `filipino-badwords-list` by Jerome Estiller.
 * The upstream list is MIT licensed. See THIRD_PARTY_NOTICES.md.
 *
 * A few context-sensitive terms from the upstream package are intentionally excluded
 * from Saintagram's active block list because they have common non-profane meanings,
 * especially in Filipino religious/community writing.
 */
const FILIPINO_BADWORDS_SOURCE = [
  "amputa",
  "animal ka",
  "bilat",
  "binibrocha",
  "bobo",
  "bogo",
  "boto",
  "brocha",
  "burat",
  "bwesit",
  "bwisit",
  "demonyo ka",
  "engot",
  "etits",
  "gaga",
  "gagi",
  "gago",
  "habal",
  "hayop ka",
  "hayup",
  "hinampak",
  "hinayupak",
  "hindot",
  "hindutan",
  "hudas",
  "iniyot",
  "inutel",
  "inutil",
  "iyot",
  "kagaguhan",
  "kagang",
  "kantot",
  "kantotan",
  "kantut",
  "kantutan",
  "kaululan",
  "kayat",
  "kiki",
  "kikinginamo",
  "kingina",
  "kupal",
  "leche",
  "leching",
  "lechugas",
  "lintik",
  "nakakaburat",
  "nimal",
  "ogag",
  "olok",
  "pakingshet",
  "pakshet",
  "pakyu",
  "pesteng yawa",
  "poke",
  "poki",
  "pokpok",
  "poyet",
  "pu'keng",
  "pucha",
  "puchanggala",
  "puchangina",
  "puke",
  "puki",
  "pukinangina",
  "puking",
  "punyeta",
  "puta",
  "putang",
  "putang ina",
  "putangina",
  "putanginamo",
  "putaragis",
  "putragis",
  "puyet",
  "ratbu",
  "shunga",
  "sira ulo",
  "siraulo",
  "suso",
  "susu",
  "tae",
  "taena",
  "tamod",
  "tanga",
  "tangina",
  "taragis",
  "tarantado",
  "tete",
  "teti",
  "timang",
  "tinil",
  "tite",
  "titi",
  "tungaw",
  "ulol",
  "ulul",
  "ungas"
] as const;

// These upstream entries are not blocked by default because they can be
// legitimate words/names in Saintagram content (for example, "Hudas" in a
// Bible reflection, "boto" when discussing a vote, or "habal-habal").
const CONTEXT_SENSITIVE_FILIPINO_TERMS = new Set<string>([
  "boto",
  "habal",
  "hudas",
  "kiki",
  "poke",
  "suso",
  "susu"
]);

export const FILIPINO_PROFANITY = FILIPINO_BADWORDS_SOURCE.filter(
  (term) => !CONTEXT_SENSITIVE_FILIPINO_TERMS.has(term)
);
